public_ip: 127.0.0.1
lan_if: br-lan
device_path: /onvif/device_service
events_path: /onvif/events

web:
  host: 127.0.0.1
  port: 8080
  static_dir: ./webui/dist
  config_path: ./webui/config

devices:
  - UID: 0001
    SerialNumber: Frame-Detector-001
    Name: Frame-Detector
    Vendor: New Tech
    Object: mid
    IP: 192.168.31.254
    Port: 9001
    Version: 1.0.0
    Model: MetalDetector
    Revision: 01
    AdapterDS: 192.168.31.254:9001
    Enabled: true
    Online: true

  - UID: 0002
    SerialNumber: Frame-Detector-002
    Name: Frame-Detector
    Vendor: New Tech
    Object: mid
    IP: 192.168.31.254
    Port: 9002
    Version: 1.0.0
    Model: MetalDetector
    Revision: 01
    Adapter: udp
    AdapterDS: 192.168.31.254:9002
    Enabled: true
    Online: true

  - UID: 0003
    SerialNumber: Frame-Detector-003
    Name: Frame-Detector
    Vendor: New Tech
    Object: mid
    IP: 192.168.31.254
    Port: 9003
    Version: 1.0.0
    Model: MetalDetector
    Revision: 01
    Adapter: udp
    AdapterDS: 192.168.31.254:9003
    Enabled: true
    Online: true

  - UID: 0004
    SerialNumber: Frame-Detector-004
    Name: Frame-Detector
    Vendor: New Tech
    Object: mid
    IP: 192.168.31.254
    Port: 9001
    Version: 1.0.0
    Model: MetalDetector
    Revision: 01
    Adapter: udp
    AdapterDS: 192.168.31.254:9004
    Enabled: true
    Online: true